/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color System
        'md-sys-color-primary': 'var(--md-sys-color-primary)',
        'md-sys-color-on-primary': 'var(--md-sys-color-on-primary)',
        'md-sys-color-primary-container': 'var(--md-sys-color-primary-container)',
        'md-sys-color-on-primary-container': 'var(--md-sys-color-on-primary-container)',
        
        'md-sys-color-secondary': 'var(--md-sys-color-secondary)',
        'md-sys-color-on-secondary': 'var(--md-sys-color-on-secondary)',
        'md-sys-color-secondary-container': 'var(--md-sys-color-secondary-container)',
        'md-sys-color-on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        
        'md-sys-color-tertiary': 'var(--md-sys-color-tertiary)',
        'md-sys-color-on-tertiary': 'var(--md-sys-color-on-tertiary)',
        'md-sys-color-tertiary-container': 'var(--md-sys-color-tertiary-container)',
        'md-sys-color-on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
        
        'md-sys-color-error': 'var(--md-sys-color-error)',
        'md-sys-color-on-error': 'var(--md-sys-color-on-error)',
        'md-sys-color-error-container': 'var(--md-sys-color-error-container)',
        'md-sys-color-on-error-container': 'var(--md-sys-color-on-error-container)',
        
        'md-sys-color-surface': 'var(--md-sys-color-surface)',
        'md-sys-color-on-surface': 'var(--md-sys-color-on-surface)',
        'md-sys-color-surface-variant': 'var(--md-sys-color-surface-variant)',
        'md-sys-color-on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'md-sys-color-surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
        'md-sys-color-surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'md-sys-color-surface-container': 'var(--md-sys-color-surface-container)',
        'md-sys-color-surface-container-low': 'var(--md-sys-color-surface-container-low)',
        'md-sys-color-surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'md-sys-color-surface-dim': 'var(--md-sys-color-surface-dim)',
        'md-sys-color-surface-bright': 'var(--md-sys-color-surface-bright)',
        
        'md-sys-color-outline': 'var(--md-sys-color-outline)',
        'md-sys-color-outline-variant': 'var(--md-sys-color-outline-variant)',
        
        'md-sys-color-shadow': 'var(--md-sys-color-shadow)',
        'md-sys-color-scrim': 'var(--md-sys-color-scrim)',
        'md-sys-color-inverse-surface': 'var(--md-sys-color-inverse-surface)',
        'md-sys-color-inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
        'md-sys-color-inverse-primary': 'var(--md-sys-color-inverse-primary)',
      },
      borderRadius: {
        'none': '0px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '28px',
        'full': '9999px',
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
      },
      fontFamily: {
        'display': ['Roboto', 'sans-serif'],
        'headline': ['Roboto', 'sans-serif'],
        'title': ['Roboto', 'sans-serif'],
        'label': ['Roboto', 'sans-serif'],
        'body': ['Roboto', 'sans-serif'],
      },
      fontSize: {
        'display-large': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'display-medium': ['45px', { lineHeight: '52px', letterSpacing: '0px' }],
        'display-small': ['36px', { lineHeight: '44px', letterSpacing: '0px' }],
        'headline-large': ['32px', { lineHeight: '40px', letterSpacing: '0px' }],
        'headline-medium': ['28px', { lineHeight: '36px', letterSpacing: '0px' }],
        'headline-small': ['24px', { lineHeight: '32px', letterSpacing: '0px' }],
        'title-large': ['22px', { lineHeight: '28px', letterSpacing: '0px' }],
        'title-medium': ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'title-small': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'label-large': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'label-medium': ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'label-small': ['11px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'body-large': ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'body-small': ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
      },
      fontWeight: {
        'regular': '400',
        'medium': '500',
      },
      boxShadow: {
        'elevation-1': '0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        'elevation-2': '0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        'elevation-3': '0px 1px 3px 0px rgba(0, 0, 0, 0.3), 0px 4px 8px 3px rgba(0, 0, 0, 0.15)',
        'elevation-4': '0px 2px 3px 0px rgba(0, 0, 0, 0.3), 0px 6px 10px 4px rgba(0, 0, 0, 0.15)',
        'elevation-5': '0px 4px 4px 0px rgba(0, 0, 0, 0.3), 0px 8px 12px 6px rgba(0, 0, 0, 0.15)',
      },
    },
  },
  plugins: [],
}